přidání requirement souboru
zdenekptak/sevilla pull request #22
Opened 2019-09-16 16:34 UTC by zdenekptak

2019-09-19 11:25 UTC, nemochovsky requested changes
Většinu z těhdle knihoven není potřeba instalovat. Jsou totiž standardní součástí Pythonu.

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +BeautifulSoup
Tenhle balíček se instaluje pod jménem `beautifulsoup4`.

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +json
Balíček `json` se instalovat nemusí. Je to jedna ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +MIMEText
Balíček `email` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +pickle
Balíček `pickle` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +smtplib
Balíček `smtplib` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +ssl
Balíček `ssl` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +sys
Balíček `sys` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-19 11:25 UTC, nemochovsky commented on requirements.txt
> +time
Balíček `time` je taky jednou ze [standardních knihoven Pythonu](https://docs.python.org/3/library/index.html).

2019-09-22 06:58 UTC, nemochovsky requested changes

2019-09-22 06:58 UTC, nemochovsky commented on requirements.txt
> +BeautifulSoup4
V názvech balíčků se rozlišují velká a malá písmena. Tenhle balík se instaluje jako [`beatifulsoup4`](https://pypi.org/project/beautifulsoup4/).

2019-09-22 14:28 UTC, zdenekptak commented on requirements.txt
> +BeautifulSoup4
opraveno

2019-09-22 14:55 UTC, nemochovsky commented
Může být zmergováno.

2019-09-24 16:22 UTC, merged